# Generated by Django 2.2.4 on 2019-08-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
